export default  {
  ADD_DRONE : 'ADD_DRONE',
  EDIT_DRONE : 'EDIT_DRONE',
  DELETE_DRONE : 'DELETE_DRONE',
  FETCH_DRONES : 'FETCH_DRONES',  
  SET_TEXT_FILTER : 'SET_TEXT_FILTER',
  SORT_BY_NAME : 'SORT_BY_NAME'    
}